[bradbury]
url = "http://br4dbury.tail8bd569.ts.net:8647"

[hellonurse]
url = "http://hellonurse.tail8bd569.ts.net:8647"

[mrs-johnson]
url = "http://mrs-johnson.tail8bd569.ts.net:8647"

[joan]
url = "http://joan.tail8bd569.ts.net:8647"

[dewey]
url = "http://mr-d3w3y.tail8bd569.ts.net:8647"
